name = "Air"
license = "MIT"
licenselink = "https://github.com/sethbergman/hugo-theme-air/blob/master/LICENSE.md"
description = "Casper theme from Ghost Foundation, Plus particles.js"
homepage = "https://sethbergman.github.io/hugo-theme-air"
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.14

[author]
  name = "sethbergman"
  homepage = "https://sethbergman.github.io/hugo-theme-air"

[original]
  name = "hugo-theme-air"
  homepage = "http://air.stackriot.com/"
  repo = "https://github.com/sethbergman/hugo-theme-air"
